### PR TITLE
[ENH] update emergent sessions names in schedule

### PR DESCRIPTION
**Pull request by Remi-Gau**

### CODE REVIEW

**Review by christinerogers — APPROVED** [review]
LGTM 👍

**Comment by Remi-Gau** [comment]
Cannot serve locally.
Will merge and fix post hoc if necessary.

**Comment by effigies** [comment]
> Cannot serve locally. Will merge and fix post hoc if necessary.

For things like this, I just set up `gh-pages` on my fork. You can change the branch it builds/serves from.

**Comment by Remi-Gau** [comment]
Ha yeah. I tend to always try things locally with jekyll but this one was resisting for more than 5 minutes.

**Comment by Remi-Gau** [comment]
Ok the program looks good but if may be even better if we had some links to the opened issues for each emergent session.

**Comment by effigies** [comment]
I was thinking it would be good to fill out and link to https://ohbm.github.io/osr2023/emergent/. Then got distracted...

**Pull request merged**
